# Generated by Django 4.2.7 on 2023-11-28 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="recommendations",
        ),
    ]
