version: '3.11'

services:
  db:
    container_name: pg_db
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - ./auth_db/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  web:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/back_end
    depends_on:
      - db
