version: '3.11'

services:
  db:
    container_name: pg_db
    image: postgres:latest
    volumes:
      - .auth_db/postgres/:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/back_end
    env_file:
      - .env
    depends_on:
      - db
