version: "3.10"
services:
  db_neocaffee:
    container_name: database_neo
    image: postgres:latest
    volumes:
      - .db_neo/postgres/:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "12345"

  web:
    container_name: neocaffee_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/backend_neo
    env_file:
      - .env
    depends_on:
      - db_neocaffee
