# Generated by Django 4.2.7 on 2023-11-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_alter_schedule_title"),
        ("storage", "0011_alter_ingredient_name_alter_readymadeproduct_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                ("minimal_limit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=255)),
                ("date_of_arrival", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemAdditionalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.additionalproduct",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_products",
                        to="storage.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailableAdditionalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.additionalproduct",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
            ],
        ),
    ]
