# Generated by Django 4.2.7 on 2023-11-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0012_additionalproduct_itemadditionalproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compositions_ingridients",
                to="storage.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="composition",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compositions",
                to="storage.item",
            ),
        ),
    ]
