# Generated by Django 4.2.7 on 2023-11-20 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0013_alter_composition_ingredient_alter_composition_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="image",
            new_name="image_category",
        ),
    ]
