# Generated by Django 4.2.7 on 2023-11-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0014_rename_image_category_image_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availableadditionalproduct",
            name="additional_product",
        ),
        migrations.RemoveField(
            model_name="availableadditionalproduct",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="itemadditionalproduct",
            name="additional_product",
        ),
        migrations.RemoveField(
            model_name="itemadditionalproduct",
            name="item",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_category",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="composition",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compositions",
                related_query_name="composition",
                to="storage.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="composition",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compositions",
                related_query_name="composition",
                to="storage.item",
            ),
        ),
        migrations.DeleteModel(
            name="AdditionalProduct",
        ),
        migrations.DeleteModel(
            name="AvailableAdditionalProduct",
        ),
        migrations.DeleteModel(
            name="ItemAdditionalProduct",
        ),
    ]
