# Generated by Django 4.2.7 on 2023-11-24 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0012_alter_readymadeproduct_image"),
        (
            "storage",
            "0015_remove_availableadditionalproduct_additional_product_and_more",
        ),
    ]

    operations = []
